# Permalinks
permalink:        pretty

# Setup
url:              http://estherleytush.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

# The tags listed as entries in the sidebar
sidebar_tags:     [general, algorithms, frontend, backend, mobile, blog]

# Fallback image and color if not overwritten for tag or post
color:            '#A85641'

author:
  name:    'Esther'

  twitter: mindpl_ace
  github:  mindplace

  # This photo will be used in the about section
  photo:          http://estherleytush.com/assets/headshot.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Esther, or [`@mindpl_ace`](https://www.twitter.com/mindpl_ace). I love coding
    and I get excited about web development, only in part due to the fact that I'm a nerd.

    I'm [`elsewhere on the internet`](http://estherleytush.com/), and I would love to
    [`hear from you`](http://estherleytush.com/contact/) about your fullstack journey.

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stack For Yourself
email: eleytush@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of resources on web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
